### ISSUE TITLE
intermittent compile issues: main_nl.cpp:8:10: fatal error: buildinfo.hpp: No such file or directory

### ISSUE THREAD

**Issue by geissonator** [openbmc/openpower-hw-diags#1]
OpenBMC CI has started hitting this intermittent build issue with the openpower-hw-diags recipe on the p10bmc machine.

```
02:35:14 | ../git/main_nl.cpp:8:10: fatal error: buildinfo.hpp: No such file or directory
02:35:14 |     8 | #include <buildinfo.hpp>
02:35:14 |       |          ^~~~~~~~~~~~~~~
02:35:14 | compilation terminated.
```

Patrick believes it may be a bug in the meson makefile (per discord discussion)
```
stwcx: Sounds like a missing DEPENDS then (which causes a race condition).
stwcx: Oh. Buildinfo is created by their own meson (the <> threw me off). But it isn’t added as a dependency in many (any?) build directives.
stwcx: https://github.com/openbmc/openpower-hw-diags/blob/eea45427d3c5976f1922711cf01a0e25ca193993/meson.build#L13
```

**Comment by williamspatrick** [comment]
Yes.  I think here and the attn meson.build need a fix so that the output of the rule that generates buildinfo.hpp is passed in as a source dependency on all of your build targets.

Note that `vcs_tag`, which is what you are using here creates a `target` (https://mesonbuild.com/Reference-manual.html#vcs_tag).  Targets are created when you run `ninja` to do the build, so target dependency relationships must be put in place.  This does appear to be the "mesonic" way to do what you are attempting, but some other repositories do similar using `configure_file` (https://mesonbuild.com/Reference-manual.html#configure_file).  I believe `configure_file` is executed when `meson` is ran and not `ninja` so the dependency is already satisfied in that case.

(I wrote the above about `vcs_tag` / `configure_file` not to say you are doing anything wrong, except the missing dependency, but to give color on why some repositories, like phosphor-logging, are generating header files without these race conditions showing up.)

**Comment by zane131** [comment]
Thanks for the clarification. I assumed `vcs_tag` and `configure_file` worked the same. Should be simple enough to add the dependencies down in this block: https://github.com/openbmc/openpower-hw-diags/blob/eea45427d3c5976f1922711cf01a0e25ca193993/meson.build#L92

**Comment by williamspatrick** [comment]
Yes.

**Comment by amboar** [comment]
Do we have a patch yet?
